Populate graphql with transaction data
dusk-network/dusk-blockchain pull request #1289
Opened 2022-02-11 08:08 UTC by goshawk-3

fixes #1284

2022-02-11 22:01 UTC, herr-seppia requested changes
RFC in reward calculation

2022-02-14 05:26 UTC, goshawk-3 commented on pkg/gql/query/blocks.go
> +				if err := encoding.ReadUint32LE(bytes.NewBuffer(note.ValueCommitment), &r); err != nil {
I'm a bit confused. Then why do you marshal it as 32-length:
```golang
func MarshalNote(r *bytes.Buffer, f *Note) error {
	if err := encoding.WriteUint8(r, f.Type); err != nil {
		return err
	}

	if err := encoding.Write256(r, f.ValueCommitment); err != nil {
		return err
	}
```

When this was raised with the team, it was said that we need `ValueCommitment`. So I'll file another issue to address this.

2022-02-14 05:34 UTC, goshawk-3 commented on pkg/core/mempool/mempool.go
> +	t.tx, err = transactions.UpdateHash(t.tx, hash)
Not needed for now, I think

2022-02-14 08:52 UTC, herr-seppia approved these changes
LGTM

2022-02-14 08:57 UTC, merged