Fix/issue 685
dusk-network/dusk-blockchain pull request #690
Opened 2020-09-25 10:52 UTC by ggoranov

2020-10-14 14:41 UTC, autholykos requested changes

2020-10-14 14:41 UTC, autholykos commented on pkg/core/consensus/collector.go
> +	acceptedBlockChan := make(chan block.Block, 500)
Please extrapolate the size of the channel buffer into a variable (which later, in a separate issue, will be filled at `init` time with some configuration)

2020-10-14 14:41 UTC, autholykos commented on pkg/core/chain/chain.go
> +	chain.blockChan = make(chan message.Message, 600)
Put the channel buffer size in a variable

2020-10-14 14:41 UTC, autholykos commented on pkg/core/chain/chain.go
> +	timer := time.NewTimer(1 * time.Second)
parametrizing the timeout might give some control when testing for the resilience of the node on adverse network conditions

2020-10-15 07:28 UTC, ggoranov commented on pkg/util/container/sharedsafe/object.go
> +	if n != nil {
I believe that (re)setting a shared object with `nil` value is a valid scenario which could be useful as specific shared state between goroutines.  `Safe` principle here is implemented with the meaning of `thread-safe`. Maybe naming should be updated.

Below is a suggestion to address the `nil` input.

```golang
func (s *Object) Set(n payload.Safe) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if n != nil {
		s.data = n.Copy()
	} else {
             s.data = nil
        }
}
```

Thoughts on that?

2020-10-15 07:48 UTC, autholykos commented on pkg/util/container/sharedsafe/object.go
> +package sharedsafe
After evaluating the reasoning behind a separate package, I am still convinced that the `sharedsafe` package does not belong in `util`. Apart that stuffing components and functions in `util` is considered an [antipattern by some and unidiomatic for go](https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common), the `sharedsafe` object has a dependency on the `Safe` interface, and therefore it belongs in the same package

2020-10-15 07:49 UTC, autholykos commented on pkg/util/container/sharedsafe/object.go
> +// Set updates last block with a full copy of the new block
This is tackled in a different commit. It would be good to rebase, so to have a cleaner commit history

2020-10-15 07:50 UTC, autholykos commented on pkg/util/container/sharedsafe/object.go
> +	if n != nil {
Fair enough. Add the possibility of a `nil` value to the comment of the method. No need to change the name

2020-10-15 09:52 UTC, ggoranov commented on pkg/util/container/sharedsafe/object.go
> +package sharedsafe
Agreed that dependency with `Safe interface` would make it pointless for us to keep it in `util` pkg. But if the `payload.Safe` interface is only `Copy() Safe` method and has no relation to P2P data schema then probably `Safe` should not be part of the P2P layer?

E.g  we ca have `Copyable` in utils at first place.

```golang
type Copyable interface {
	// Copy performs a deep copy of an object
	Copy() Copyable
}

```

2020-10-16 09:46 UTC, autholykos approved these changes
LGTM

2020-10-16 09:46 UTC, merged